# version: 2.1
# orbs:
#   browser-tools: circleci/browser-tools@1.4.0
# jobs:
#   # BUILD:
#   #   working_directory: ~/resume-website
#   #   docker:
#   #       - image: cimg/node:16.13.2
#   #   steps:
#   #       - checkout
#   #       # Merge changes to release branch
#   #       # Swap to release branch
#   #       # Build
#   #       # - npm run build
#   #       # Push changes to release branch
#   TEST:
#     # requires:
#     #     - BUILD
#     working_directory: ~/resume-website
#     docker:
#         - image: cimg/node:16.13.2-browsers
#     steps:
#         # Install chrome for testing
#         - browser-tools/install-chrome
#         - browser-tools/install-chromedriver      
#         # Confirm browsers were setup
#         - run:
#             name: Check browser install
#             command: |
#               google-chrome --version
#               chromedriver --version
#         # Checkout the code from the branch into the working_directory
#         - checkout
#         # Log the current branch
#         - run:
#             name: Show current branch
#             command: echo ${CIRCLE_BRANCH}
#         # Restore local dependencies from cache
#         - restore_cache:
#             keys:
#             - v1-dependencies-{{ checksum "package-lock.json" }}
#             - v1-dependencies-
#         # Install project dependencies
#         - run:
#             name: Install local dependencies
#             command: npm install
#         # Cache local dependencies if they don't exist
#         - save_cache:
#             key: v1-dependencies-{{ checksum "package-lock.json" }}
#             paths:
#                 - node_modules
#         # # Lint the source code
#         # - run:
#         #     name: Linting
#         #     command: npm run lint
#         # Test the source code
#         - run:
#             name: Testing
#             command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
#         # End to End test
#         # - run:
#         #     name: End to End Test
#         #     command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
#         # - run:
#         #     name: Build
#         #     command: |
#         #         npm run build
#   DEPLOY:
#     requires:
#         # - BUILD
#         - TEST
#     working_directory: ~/resume-website
#     docker:
#         - image: cimg/node:16.13.2
#     steps:
#         - checkout
#         - run:
#             name: Deploy
#             # ToDo: find better way of dealing with changes to package-lock.json, currently just dropping the changes...
#             command: |
#                 sudo apt-get update
#                 sudo apt-get -qq install git-ftp
#                 echo "Checking for changes..."
#                 git status -uno --porcelain
#                 echo "Dropping changes & deploying site..."
#                 git reset --hard 
#                 git ftp init --user "${username}" --passwd "${password}" ${ftp_location}
# workflows:
#   version: 2
#   master-deploy:
#     jobs:
#       - BUILD:
#           filters:
#             branches:
#               only: master
#       - TEST:
#           filters:
#             branches:
#               only: release
#       - DEPLOY:
#           filters:
#             branches:
#               only: release